"use strict";
const ActionTypes = {
    // LOGIN / CREDENTIAL RELATED ACTIONS
    LOGIN: "LOGIN",
    AUTHORIZE: "AUTHORIZE",
    DEAUTHORIZE: "DEAUTHORIZE",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    // FORMS
    FORM_FIELD_UPDATE: "FORM_FIELD_UPDATE",
    CLEAR_FORM: "CLEAR_FORM",
    FORM_SUBMISSION: 'FORM_SUBMISSION',
    FORM_SUBMISSION_FAIL: 'FORM_SUBMISSION_FAIL',
    FORM_SUBMISSION_SUCCESS: 'FORM_SUBMISSION_SUCCESS',
    // API REQUESTS
    BATCH_PULL_START: "BATCH_PULL_START",
    BATCH_PULL_SUCCESS: "BATCH_PULL_PROGRESS",
    BATCH_PULL_FAIL: "BATCH_PULL_END",
    API_REQUEST_START: "API_REQUEST_START",
    API_REQUEST_END: "API_REQUEST_END",
    // RECORDS
    APPEND_RECORDS: 'APPEND_RECORDS',
    CLEAR_RECORDS: 'CLEAR_RECORDS',
    // GLOBAL STATE
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_ALERT: "SHOW_ALERT",
    DISMISS_ALERT: "DISMISS_ALERT",
    FADE_ALERT: "FADE_ALERT",
    // DATATABLE
    PAGING_GO_TO_PAGE: "PAGING_GO_TO_PAGE"
};

module.exports = ActionTypes;