"use strict";

module.exports = {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    PROFILE: 'PROFILE',
    TIME_BLOCK_CREATE: 'TIME_BLOCK_CREATE',
    TIME_BLOCK_EDIT: 'TIME_BLOCK_EDIT',
    USER_EDIT: 'USER_EDIT',
    USER_CREATE: 'USER_CREATE'
};